version: 2
updates:
  - package-ecosystem: "npm"
    assignees:
      - friedemannsommer
    commit-message:
      prefix: "chore"
      include: "scope"
    directory: "/"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    reviewers:
      - friedemannsommer
    schedule:
      day: friday
      interval: weekly
      timezone: "Etc/UTC"

  - package-ecosystem: "github-actions"
    assignees:
      - friedemannsommer
    commit-message:
      prefix: "ci"
      include: "scope"
    directory: "/"
    groups:
      github-actions:
        patterns:
          - "*"
    reviewers:
      - friedemannsommer
    schedule:
      day: friday
      interval: weekly
      timezone: "Etc/UTC"
