name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [20, 22, 24]
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: actions/setup-node@v6.0.0
        with:
          cache: 'npm'
          node-version: ${{ matrix.node-version }}
      - run: npm ci --no-fund --no-audit
      - name: Run checks
        run: npm run check:ci
      - name: Build package
        run: npm run build
      - name: Run tests
        run: npm run test

  release:
    name: Release
    needs:
      - check
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: github.repository_owner == 'friedemannsommer' && github.ref_name == 'main'
    concurrency: '${{ github.workflow }}-${{ github.ref }}'
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: actions/setup-node@v6.0.0
        with:
          cache: 'npm'
          node-version-file: '.node-version'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci --no-fund --no-audit
      - name: Create release PR or publish
        uses: changesets/action@v1.5.3
        with:
          title: 'ci(changesets): package release'
          commit: 'ci(changesets): version package'
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
